version: "3.7"

services:
  django_app:
    build: ./django_app
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/django_app
      - /django_app/.venv
    environment:
      IS_PRODUCT: 'no'
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900
